"use client"
import { Inter } from "next/font/google";
// import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import { connect, Provider, useSelector } from "react-redux";
import { appStore } from "@/redux/store/appStore";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";
import RootLayoutWapper from "./layoutWrapper";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const state = useSelector((state)=>{
  //   return state
  // })
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={appStore}>
          <RootLayoutWapper>
            {children}
          </RootLayoutWapper>
        </Provider>       
        </body>
    </html>
  );
}

